// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm3lBEVlM1_KhKj-n5htBbJq0N3kv3WF8',
    appId: '1:1064639326328:web:da90e7b2bb4a599288258d',
    messagingSenderId: '1064639326328',
    projectId: 'equips-d40b3',
    authDomain: 'equips-d40b3.firebaseapp.com',
    storageBucket: 'equips-d40b3.appspot.com',
    measurementId: 'G-NEGNHDY31D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgIR-hJHQEcFKb4n363yQ7oWlnrnA5iaw',
    appId: '1:1064639326328:android:ae38b2a258e1b9f888258d',
    messagingSenderId: '1064639326328',
    projectId: 'equips-d40b3',
    storageBucket: 'equips-d40b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7IC35g8OmKXjPLz8Vl6kNXvX-x8UEocU',
    appId: '1:1064639326328:ios:422a40be0e6d133d88258d',
    messagingSenderId: '1064639326328',
    projectId: 'equips-d40b3',
    storageBucket: 'equips-d40b3.appspot.com',
    iosBundleId: 'com.example.equipsV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm3lBEVlM1_KhKj-n5htBbJq0N3kv3WF8',
    appId: '1:1064639326328:web:ee6cd5bef4bdfa7788258d',
    messagingSenderId: '1064639326328',
    projectId: 'equips-d40b3',
    authDomain: 'equips-d40b3.firebaseapp.com',
    storageBucket: 'equips-d40b3.appspot.com',
    measurementId: 'G-KMM2KYT49G',
  );
}
